name: Deploy MERN App to Cloud Run

on:
  push:
    branches:
      - main  # deploy only on main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Authenticate to GCP using service account
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Step 3: Set up gcloud CLI
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: mern-pipeline-prod

      # Step 4: Optional – Debug active account
      - name: Show active gcloud account
        run: gcloud auth list

      # Step 5: Deploy to Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mern-pipeline-app \
            --source . \
            --region us-central1 \
            --allow-unauthenticated

      # Step 6: Get deployed service URL
      - name: Print Cloud Run URL
        run: |
          gcloud run services describe mern-pipeline-app \
            --region us-central1 \
            --format="value(status.url)"
